//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nikolay.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompletedProjects
    {
        public int ProjectId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ProjectName { get; set; }
        public System.DateTime CompletionDate { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
