//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nikolay.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HousePrefer
    {
        public int Id { get; set; }
        public Nullable<int> Komnat { get; set; }
        public Nullable<int> Etajey { get; set; }
        public Nullable<int> Sanuzlov { get; set; }
        public Nullable<int> Vannih { get; set; }
        public Nullable<int> Balkonov { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Stoimost { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
